coverage:
  status:
    patch: off
    project:
      default:
        target: 50%
        threshold: 10%
        if_ci_failed: error

ignore:
  - "**/pkg/api/**" # ignore folders and all its contents
  - "**/tests/**"
  - "**/internal/api/v1/http/server/*"
  - "**/mocks/**"         # glob accepted
  - "**/*_test.go"         # glob accepted