app:
  name: pvz
  env: prod

cache:
  pvz_list_ttl: 10m

api:
  http:
    port: 8080
    read_timeout: 5s
    write_timeout: 5s
    idle_timeout: 3m

  grpc:
    port: 3000
  prometheus:
    port: 9000

swagger:
  port: 2000

auth:
  password_cost_bcrypt: 13
  access_token_ttl: 2h

postgres:
  max_open_conns: 40
  min_idle_conns: 10
  conn_max_idle_time: 5m
  conn_max_lifetime: 10m