env: prod

api:
  http:
    port: 8080
    read_timeout: 5s
    write_timeout: 5s
    idle_timeout: 3m
    max_header_bytes: 65000
  grpc:
    port: 3000

swagger:
  port: 2000

auth:
  password_cost_bcrypt: 13
  access_token_ttl: 2h

postgres:
  max_open_conns: 40
  max_idle_conns: 10
  conn_max_idle_time: 5m
  conn_max_lifetime: 10m