name: coverage

on:
  push:
    branches: ["*"]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.24.0

      - name: Up pvz
        run: make up-pvz

      - name: Run tests
        run: ./scripts/coverage.sh

      - name: Down pvz
        run: make down-pvz

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
